import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@styles/globals.css";
import RootStyleRegistry from "./mantine";
import AppProgressBar from "@components/common/progress-bar";
import ReactQueryProvider from "../providers/ReactQueryClientProvider";
import { DataSourceProvider } from "../providers/DataSourceProvider";
import supabaseServer from "@lib/supabase/server";
import { AuthProvider } from "@/lib/auth/auth.provider";
import { AuthProvider as AuthProviderS } from "@/providers/AuthProvider";
import { getSession } from "@/lib/auth/auth.service";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function  RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
 return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <AuthProvider session={session} >
          <ReactQueryProvider>
            <RootStyleRegistry>
              <AppProgressBar>
                <DataSourceProvider>{children}</DataSourceProvider>
              </AppProgressBar>
            </RootStyleRegistry>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
